spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devlink
    username: your_db_user
    password: your_db_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080